# CONVERTED FROM THE ORIGINAL FOCAL PROGRAM AND MODIFIED
# FOR EDUSYSTEM 70 BY DAVID AHL, DIGITAL
# MODIFIED FOR 8K MICROSOFT BASIC BY PETER TURNBULL
puts  "TRY YOUR HAND AT GOVERNING ANCIENT SUMERIA"
puts  "SUCCESSFULLY FOR A 10-YR TERM OF OFFICE."
